package main

import (
	"errors"
)

func commandExit() error {
	return errors.New("Try error")
}
